apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  selector:
    app: nginx
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 2
  ports:
    - port: 80
      targetPort: 80
