# Run Every minute CronJob
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: alpine
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - sleep 80 ;date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure