apiVersion: v1
kind: Pod
metadata:
  name: with-pod-affinity
spec:
  containers:
    - name: c1
      image: alpine
      command: [ "sleep","1000s" ]
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: security
                operator: Exists
                values:
                  - s1
          topologyKey: kubernetes.io/hostname