apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: security
                operator: In
                values:
                  - S1
          topologyKey: kubernetes.io/hostname
  containers:
    - name: c1
      image: alpine
      command: ["sleep","1000s"]


