apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
   containers:
    - name: c1
      image: nginx
      {{- with .Values.env }}
      env:
        {{- toYaml . | nindent 8 }}
      {{- end }}

