apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
   containers:
    - name: c1
      image: nginx
      env:
        name: app_url
        value: {{ .Values.app_url }}
