apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
   containers:
    - name: c1
      image: chaitu1812/nginx
      env:
        - name: nginx_version
          value: "1.4.3"


