apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name1: nginx1
    name2: {{ .Values.name2 }}
spec:
   containers:
    - name: c1
      image: nginx
      env:
        name: app_url
        value: {{ .Values.app_url }}
