apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  restartPolicy: Never
  initContainers:
    - name: c1
      image: alpine
      command:
        - "sh"
        - "-c"
        - "sleep 10 && exit 1"
    - name: c2
      image: alpine
      command: ["sleep","10"]
  containers:
    - name: c3
      image: nginx
