apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  restartPolicy: Never
  initContainers:
    - name: c1
      image: alpine
      command:
        - "sh"
        - "-c"
        - "echo 'This is container1' > /data/index.html"
      volumeMounts:
        - name: vol
          mountPath: /data
    - name: c2
      image: alpine
      command:
        - "sh"
        - "-c"
        - "echo 'This is container2' >> /data/index.html"
      volumeMounts:
        - name: vol
          mountPath: /data
  containers:
    - name: c3
      image: nginx
      volumeMounts:
        - name: vol
          mountPath: /usr/share/nginx/html/
  volumes:
    - name: vol
      emptyDir: {}
