apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: first
          emptyDir: {}
      containers:
        - name: c1
          ports:
            - containerPort: 80
          image: nginx
          volumeMounts:
            - name: first
              mountPath: /usr/share/nginx/html
