apiVersion: v1
kind: PersistentVolume
metadata:
  name: chaitu-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/nginx-1
  persistentVolumeReclaimPolicy: Delete
