apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/nginx-1
  persistentVolumeReclaimPolicy: Delete
  claimRef:
    name: chaitu
    namespace: default
