apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 172.31.89.244
    path: /tmp/nfs_volume1
  persistentVolumeReclaimPolicy: Delete
