apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
spec:
  resources:
    requests:
      storage: 1Gi
  nfs:
    server: 172.31.89.244
    path: /tmp/nfs_volume
  accessModes:
    - ReadWriteOnce
