apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}
spec:
  containers:
    - name: c1
      image: {{ .Values.Image.name }}
      ports:
        - containerPort: {{ .Values.containerPort }}