apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}
spec:
  containers:
    - name: c1
      image: {{ .Values.Image.name }}
      env:
        - name: Host
          value: "chaitu"
      ports:
        - containerPort: {{ .Values.containerPort }}