apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  volumes:
    - name: example1
      secret:
        secretName:  example1
  containers:
    - name: c1
      image: alpine
      command: ["sleep","10000"]
      envFrom:
        - secretKeyRef:
            name: example1
      volumeMounts:
        - name: example1
          mountPath: /chaitu/example1

