apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-06d17cb1766457a19
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeName: ebs-static
---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  nodeName: ip-172-31-41-99.ec2.internal
  volumes:
    - name: nginx-vol
      persistentVolumeClaim:
        claimName: ebs-pvc
  containers:
    - name: c1
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-vol
          mountPath: /usr/share/nginx/html






