apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: c1
      image: nginx
      livenessProbe:
        tcpSocket:
          port: 80
        initialDelaySeconds: 20
        periodSeconds: 10
        failureThreshold: 1

