apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: c1
      image: nginx
      readinessProbe:
        exec:
          command:
            - /bin/bash
            - -c
            - /usr/share/nginx/html/index.html
        initialDelaySeconds: 15
        periodSeconds: 10
