apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: c1
      image: nginx
      livenessProbe:
        httpGet:
          path: /index1.html
          port: 80
        initialDelaySeconds: 25
        periodSeconds: 10
        failureThreshold: 1

