apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: c1
      image: nginx
      livenessProbe:
        exec:
          command:
            - /bin/bash
            - -c
            - cat /usr/share/nginx/html/index.html
        initialDelaySeconds: 20
        periodSeconds: 10
