apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: c1
      image: nginx
      startupProbe:
       httpGet:
         path: /index1.html
         port: 80
       initialDelaySeconds: 10
       failureThreshold: 5
       periodSeconds: 5


