apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  tolerations:
    - operator: Exists
      effect: NoSchedule
  containers:
    - name: alpine
      image: alpine
      command: ["sleep","10000"]