apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  nodeName: ip-172-31-91-104.ec2.internal
  tolerations:
    - operator: Exists
      effect: NoExecute
  containers:
    - name: alpine
      image: alpine
      command: ["sleep","10000"]