apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  nodeSelector:
    app: node2
  tolerations:
    - operator: Exists
  containers:
    - name: alpine
      image: alpine
      command: ["sleep","10000"]