apiVersion: batch/v1
kind: Job
metadata:
  name: kubernetes-job-example
  labels:
    jobgroup: jobexample
spec:
  completions: 3
  parallelism: 2
  template:
    metadata:
      name: kubejob
      labels:
        jobgroup: jobexample
    spec:
      containers:
        - name: c
          image: docker.io/alpine
          command: ["sh","-c","sleep 10 & exit 1"]
      restartPolicy: OnFailure