apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-{{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Release.Namespace }}
  {{- if eq .Release.Namespace "dev" }}
  replicas: 2
  {{- else if eq Release.Namespace "prod" }}
  repliacs: 3
  {{- else }}
  repliacs: 1
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Release.Namespace }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          env: {{- toYaml .Values.envs | nindent 12 }}
          image: chaitu1812/expense-{{ .Release.Name }}
          ports:
            - containerPort: {{ .Values.service.containerPort }}








