apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    name: nginx
spec:
   containers:
    - name: c1
      image: chaitu1812/nginx:{{ .Values.tag_name }}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    name: nginx
  type: NodePort
  ports:
    - targetPort: 80

