apiVersion: v1
kind: Pod
metadata:
  name: pod1
  annotations:
    app: nginx
    # "helm.sh/resource-policy": keep
spec:
  containers:
    - name: c1
      image: nginx
      ports:
        - containerPort: 80


