apiVersion: v1
kind: Pod
metadata:
  name: pod1
  annotations:
    app: nginx
  labels:
    app: nginx
    # "helm.sh/resource-policy": keep
spec:
  containers:
    - name: c1
      image: nginx
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: service1
  annotations:
    "helm.sh/resource-policy": keep
spec:
  selector:
    app: nginx1
  ports:
    - port: 80
      targetPort: 8080


