apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy1
  labels:
    app: nginx-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: first
          persistentVolumeClaim:
            claimName: pvc1
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: first
              mountPath: /tmp/nginx-vol
