apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
  volumeName: pvc-58d2051f-4511-4bfd-9918-54df2c4e0093
  storageClassName: nfs-storageclass