apiVersion: v1
kind: Pod
metadata:
  name: with-pod-affinity
spec:
  containers:
    - name: c1
      image: alpine
      command:
        - "sh"
        - "-c"
        - "if [ -z $name ]; then echo '$name env is missing' && exit 1; else sleep 10000s;fi"