apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: c1
      image: alpine
      command:
        - "sh"
        - "-c"
        - "echo this is chaithanya > /tmp/chaitu"



