apiVersion: v1
kind: ServiceAccount
metadata:
  name: debug
  namespace: prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: prod
  name: prod-reader
rules:
  - apiGroups: [""]
    resources: ["pods","services","deployments"]
    verbs: ["get", "watch", "list","delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-ns-pod-reader-to-debug-sa
  namespace: prod
roleRef:
  kind: Role
  name: prod-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: debug
    namespace: prod

---
apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: prod
spec:
  serviceAccountName: debug
  containers:
    - name: debug
      image: chaitu1812/kubectl-cli
      command: ["sleep","100000"]



