apiVersion: v1
kind: ServiceAccount
metadata:
  name: debug
  namespace: default


---
apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: default
spec:
  serviceAccountName: debug
  nodeName: ip-172-31-34-19.ap-south-1.compute.internal
  containers:
    - name: debug
      image: chaitu1812/kubectl-cli

